import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { CartService } from '../../services/cart-service';
import { ButtonModule } from 'primeng/button';
import { InputTextModule } from 'primeng/inputtext';
import { CardModule } from 'primeng/card';
import { DividerModule } from 'primeng/divider';
import { Router } from '@angular/router';
import { MessageService } from 'primeng/api';
import { ToastModule } from 'primeng/toast';
import { OrderModel } from '../../models/orders-model';
import { OrderItemModel } from '../../models/order-item-model';
import { PostOrderModel } from '../../models/post-order-model';
import { OrderService } from '../../services/order-service';

@Component({
  selector: 'app-checkout',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    ButtonModule,
    InputTextModule,
    CardModule,
    DividerModule,
    ToastModule
  ],
  templateUrl: './checkout.html',
  styleUrl: './checkout.scss',
  providers: [MessageService]
})
export class Checkout {
  private cartService = inject(CartService);
  private router = inject(Router);
  private messageService = inject(MessageService);
  private formBuilder = inject(FormBuilder);
  private orderService = inject(OrderService);

  products = this.cartService.cartItems;
  totalPrice = this.cartService.totalPrice;

  checkoutForm: FormGroup;

  constructor() {
    this.checkoutForm = this.formBuilder.group({
      // Credit Card Fields
      cardholderName: ['', [Validators.required, Validators.minLength(3)]],
      cardNumber: ['', [Validators.required, Validators.pattern(/^\d{16}$/)]],
      expiryDate: ['', [Validators.required, Validators.pattern(/^\d{2}\/\d{2}$/)]],
      cvv: ['', [Validators.required, Validators.pattern(/^\d{3}$/)]],

      // Address Fields
      street: ['', [Validators.required, Validators.minLength(5)]],
      city: ['', [Validators.required, Validators.minLength(2)]],
      state: ['', [Validators.required, Validators.minLength(2)]],
      postalCode: ['', [Validators.required, Validators.pattern(/^\d{5,9}$/)]],
      country: ['', [Validators.required, Validators.minLength(2)]],
      phone: ['', [Validators.required, Validators.pattern(/^\d{9,15}$/)]]
    });
  }

  processPayment(): void {
    if (!this.checkoutForm.valid) {
      this.messageService.add({
        severity: 'error',
        summary: 'Form Error',
        detail: 'Please fill in all fields correctly'
      });
      return;
    }

    if (this.products().length === 0) {
      this.messageService.add({
        severity: 'error',
        summary: 'Empty Cart',
        detail: 'Your cart is empty'
      });
      return;
    }

    // Process payment
    const formData = this.checkoutForm.value;
    const orderData: PostOrderModel = {
      id: -1, // Placeholder ID - in a real app, this would be generated by the backend
      userId: 1, // Assuming a default user ID for demo purposes
      orderItems: this.products().map(item => ({ orderId: item.orderId, productId: item.productId, quantity: item.quantity, userId: 1 })),
      orderSum: this.totalPrice(),
      status: 'pending',
      orderDate: new Date()
    };

    console.log('Processing order:', orderData);
    this.orderService.createOrder(orderData).subscribe({
      next: () => {
        this.messageService.add({
          severity: 'success',
          summary: 'Success',
          detail: `Order placed successfully! Total: ${this.totalPrice()} $`
        });
      },
      error: (err) => {
        console.error('Payment failed:', err);
        this.messageService.add({
          severity: 'error',
          summary: 'Payment Failed',
          detail: 'There was an issue processing your payment. Please try again.'
        });
      }
    });
  
    // Clear cart after successful order
    setTimeout(() => {
      this.cartService.clearCart();
      this.router.navigate(['/show-products']);
    }, 2000);

  }

  goBack(): void {
    this.router.navigate(['/cart']);
  }
}
